apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    app: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
      - name: stock-service
        image: sourav40/stock-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 130
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
        env:
        - name: APP_PROFILE
          valueFrom:
            configMapKeyRef:
              name: app
              key: APP_PROFILE
        - name: MYSQL_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app
              key: DATABASE_URL
        - name: MYSQL_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: app
              key: DATABASE_PORT
        - name: MYSQL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: app
              key: STOCK_DATABASE_NAME
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysqldb
              key: DATABASE_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb
              key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  labels:
    app: stock-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: stock-service
  type: ClusterIP